[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:daphne]
command=python -m daphne -b 0.0.0.0 -p 8000 config.asgi:application
autostart=true
autorestart=true