# Generated by Django 6.0.6 on 2026-07-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='target_ip',
            field=models.CharField(max_length=255),
        ),
    ]
